language: go
go:
- 1.5
- 1.4.2
before_install:
- curl -sLOf https://raw.githubusercontent.com/MStoykov/fmtpolice/master/fmtpolice
- curl -sLOf https://raw.githubusercontent.com/MStoykov/fmtpolice/master/coverage
- go get github.com/axw/gocov/gocov github.com/mattn/goveralls
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
before_script:
- bash fmtpolice
- go vet ./...
script:
- bash coverage -v
after_script:
- "$HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci"
notifications:
  slack:
    secure: JqKpVVysK6jtoSjUItXUrtWz6wsLyx432/x0mElHsgKxqXPLh0WH4Mn7SyiL4kY0wbiDEuaNUGmr1OxOBanClv6L/i2FNU/f0D6WgogYhb7jjda6d3gmSgjf3Gzd0IWmP6kUeNX1cl1l8x2Qk4IsAr/Y63iBe1/WG4fpUz/NKcc=
